name: Publish charm

on:
  workflow_call:
    secrets:
      CHARMCRAFT_AUTH:
        required: true

jobs:
  publish-charm:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install charmcraft
        run: sudo snap install charmcraft --classic

      - name: Fetch Tested Charm
        uses: actions/download-artifact@v4
        with:
          name: built-charm
      
      - name: Get Charm Under Test Path
        id: charm-path
        run: echo "charm_path=$(find . -name '*.charm' -type f -print)" >> $GITHUB_OUTPUT
  
      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@2.7.0
        with:
          built-charm-path: ${{ steps.charm-path.outputs.charm_path }}
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: edge
  
      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
